package com.example.taskmaster.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;

import java.util.*;

@DynamoDBTable(tableName = "taskmaster")
public class Task
{
    private String id;
    private String title;
    private String description;
    private String status;
    private String assignee;

    private List<String> historyList;

    public Task() {}

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return this.title;
    }
    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public String getAssignee() {
        return assignee;
    }
    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    @DynamoDBAttribute
    public List<String> getHistory() {
        return this.historyList;
    }
    public void setHistory(String actionTaken)
    {
        if (this.historyList == null)
        {
            historyList = new ArrayList<>();
        }
        String date = new Date(System.currentTimeMillis()).toString();
        String action = actionTaken;
        String data = date + action;
        this.historyList.add(data);
    }

//    public static class History
//    {
//        private String date;
//        private String actionTaken;
//
//        public History() {}
//
//        public History(String actionTaken)
//        {
//            this.date =
//            this.actionTaken = actionTaken;
//        }
//
//        @DynamoDBAttribute
//        public String getDate()
//        {
//            return this.date;
//        }
//
//        @DynamoDBAttribute
//        public String getAction() {
//            return actionTaken;
//        }
//    }
}
